### ISSUE TITLE
can I use this in python 3

### ISSUE THREAD

**Issue by skashish** [alexcouper/bash#5]
I installed this by `pip install bash`.
After that I can Import bash in python 2.x using `from bash import bash`but not in python3.

is there a way i can use this in python3? 

Thanks!

**Comment by alexcouper** [comment]
What version of python 3 are you using?

It's tested on travis using 3.4 and 3.5: https://travis-ci.org/alexcouper/bash/builds/106055033

**Comment by skashish** [comment]
I'm on Python 3.4.3

**Comment by skashish** [comment]
Oh! I just did `pip3 install bash` and its working now. Thanks!
